# Generated by Django 2.0.7 on 2018-07-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=280)),
                ('content', models.TextField()),
                ('status', models.PositiveSmallIntegerField(choices=[(4, 'Deleted'), (2, 'Published'), (3, 'To be reviewed'), (1, 'Not published yet')], default=1)),
            ],
        ),
    ]
