# DO NOT EDIT THIS FILE MANUALLY
# THIS FILE IS AUTO-GENERATED
# MANUAL CHANGES WILL BE DISCARDED
# PLEASE READ GARUDA DOCS
from garuda.proto.garuda_pb2 import Article, Void  # NOQA
from garuda.sample.core.auto_crud import (  # NOQA
    read_article,
    delete_article,
    create_article,
    update_article,
    read_articles_filter,
)


def article_to_dict(obj):
    # Cycle through fields directly
    d = {  }
    if obj is None:
        return d
    is_dj_obj = obj.__module__.endswith('models')
    foriegn_keys = []
    for field in ['content', 'id', 'status', 'title']:  # NOQA
        value = getattr(obj, field, None)
        if field in [None, 'None']:
            continue
        d[field] = value
        if is_dj_obj and (field == 'id' or field in foriegn_keys):
            d[field] = str(value)
        elif is_dj_obj and field in ['created_on', 'updated_on']:
            d[field] = value.isoformat()
    return d


class ArticleGaruda:
    def ReadArticlesFilter(self, void, context):
        objs = read_articles_filter()
        return [Article(
            **article_to_dict(obj)) for obj in objs]

    def ReadArticle(self, id, context):
        obj = read_article(id=id.id)
        return Article(**article_to_dict(obj))

    def CreateArticle(self, obj, context):
        obj = create_article(**article_to_dict(obj))
        return Article(**article_to_dict(obj))

    def UpdateArticle(self, obj, context):
        obj_dict = article_to_dict(obj)
        del obj_dict['id']
        obj = update_article(obj.id, **obj_dict)
        return Void()

    def DeleteArticle(self, id, context):
        delete_article(id.id)
        return Void()