# DO NOT EDIT THIS FILE MANUALLY
# THIS FILE IS AUTO-GENERATED
# MANUAL CHANGES WILL BE DISCARDED
# PLEASE READ GARUDA DOCS
from garuda_dir.garuda_pb2 import LogEntry, Void  # NOQA
from django.contrib.admin.auto_crud import (  # NOQA
    read_logentry,
    delete_logentry,
    create_logentry,
    update_logentry,
    read_logentries_filter,
)


def logentry_to_dict(obj):
    # Cycle through fields directly
    d = {  }
    if obj is None:
        return d
    is_dj_obj = obj.__module__.endswith('models')
    foriegn_keys = ['content_type_id', 'user_id']
    for field in ['action_flag', 'action_time', 'change_message', 'content_type_id', 'id', 'object_id', 'object_repr', 'user_id']:  # NOQA
        value = getattr(obj, field, None)
        if field in [None, 'None']:
            continue
        d[field] = value
        if is_dj_obj and (field == 'id' or field in foriegn_keys):
            d[field] = str(value)
        elif is_dj_obj and field in ['created_on', 'updated_on']:
            d[field] = value.isoformat()
    return d


class LogEntryGaruda:

    def ReadLogEntrysFilter(self, void, context):
        objs = read_logentries_filter()
        return [LogEntry(
            **logentry_to_dict(obj)) for obj in objs]

    def ReadLogEntry(self, id, context):
        obj = read_logentry(id=id.id)
        return LogEntry(**logentry_to_dict(obj))

    def CreateLogEntry(self, obj, context):
        obj = create_logentry(**logentry_to_dict(obj))
        return LogEntry(**logentry_to_dict(obj))

    def UpdateLogEntry(self, obj, context):
        obj_dict = logentry_to_dict(obj)
        del obj_dict['id']
        obj = update_logentry(obj.id, **obj_dict)
        return Void()

    def DeleteLogEntry(self, id, context):
        delete_logentry(id.id)
        return Void()