# DO NOT EDIT THIS FILE MANUALLY
# THIS FILE IS AUTO-GENERATED
# MANUAL CHANGES WILL BE DISCARDED
# PLEASE READ GARUDA DOCS
from django.contrib.admin.models import LogEntry  # NOQA
GARUDA_IGNORE_FIELDS = ['created_on', 'updated_on', 'id']  # NOQA


def read_logentry(*args, **kwargs):
    try:
        return LogEntry.objects.get(*args, **kwargs)
    except LogEntry.DoesNotExist:
        return None


def read_logentries_filter(*args, **kwargs):
    return LogEntry.objects.filter(*args, **kwargs)


def create_logentry(*args, **kwargs):
    for ignore_field in GARUDA_IGNORE_FIELDS:
        if ignore_field in kwargs:
            del kwargs[ignore_field]
    for key in list(kwargs):
        if kwargs[key] in [None, 'None', '']:
            del kwargs[key]
    return LogEntry.objects.create(*args, **kwargs)


def update_logentry(id, *args, **kwargs):
    for ignore_field in GARUDA_IGNORE_FIELDS:
        if ignore_field in kwargs:
            del kwargs[ignore_field]
    for key in list(kwargs):
        if kwargs[key] in [None, 'None', '']:
            del kwargs[key]
    return LogEntry.objects.filter(id=id).update(*args, **kwargs)


def delete_logentry(id):
    return LogEntry.objects.get(id=id).delete()